
CREATE TABLE Clients (
    ClientID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Password VARCHAR(225) NOT NULL, 
    Address VARCHAR(225) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Orders (
    OrderID INT PRIMARY KEY AUTO_INCREMENT,
    Preference VARCHAR(100) NOT NULL,
    BeanType VARCHAR(100) NOT NULL,
    Quantity INT NOT NULL,
    GrindOption VARCHAR(100) NOT NULL,
    Delivery VARCHAR(100) NOT NULL,
    ClientID INT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
);


